import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://admin.onechanneladmin.com/signin?returnUrl=%2F');
  await page.getByRole('textbox', { name: 'Email address' }).click();
  await page.getByRole('textbox', { name: 'Email address' }).fill('princy@onechanneladmin.com');
  await page.locator('input[name="password"]').click();
  await page.locator('input[name="password"]').fill('beR60ElTpm0?YbW');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('button', { name: 'Catalog' }).click();
  await page.getByRole('link', { name: 'Brands' }).click();
  await page.getByRole('row', { name: ' Brand   Alias   Status' }).getByRole('checkbox').click();
  await page.getByRole('columnheader', { name: ' ' }).locator('i').click();
  await page.getByText('Unselect All').click();
  await page.getByRole('button', { name: ' Columns' }).click();
  await page.locator('.field-checkbox > .p-checkbox > .p-checkbox-box').click();
  await page.locator('.p-checkbox-box.p-highlight').first().click();
  await page.getByRole('button', { name: 'Apply' }).click();
  await page.getByRole('button', { name: ' Columns' }).click();
  await page.getByRole('button', { name: 'Reset' }).click();
  await page.getByRole('button', { name: ' Export' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('textbox', { name: 'Report Name' }).click();
  await page.getByRole('textbox', { name: 'Report Name' }).fill('one');
  await page.getByRole('button', { name: 'Create Report' }).click();
  await page.getByRole('button', { name: 'Create Report' }).click();
  await page.getByRole('button', { name: ' Add New' }).click();
  await page.getByRole('textbox', { name: 'Enter Brand Name' }).click();
  await page.locator('.p-dropdown.p-component.p-inputwrapper.p-focus > .p-dropdown-trigger').click();
  await page.getByRole('option', { name: '1CA', exact: true }).click();
  await page.getByRole('textbox', { name: 'Brand *' }).click();
  await page.getByRole('textbox', { name: 'Brand *' }).fill('https://admin.onechanneladmin.com/products/brands');
  await page.getByRole('textbox', { name: 'Enter Email' }).click();
  await page.getByRole('textbox', { name: 'Enter Email' }).fill('princy@onechanneladmin.com');
  await page.getByRole('textbox', { name: 'Enter Contact Name' }).click();
  await page.getByRole('textbox', { name: 'Enter Contact Name' }).fill('one');
  await page.locator('.p-inputtext.p-component.p-inputmask').click();
  await page.getByRole('button', { name: ' Submit' }).click();
  await page.getByRole('button', { name: ' Add New' }).click();
  await page.getByRole('textbox', { name: 'Enter Brand Name' }).click();
  await page.getByRole('textbox', { name: 'Enter Brand Name' }).fill('onechan');
  await page.getByRole('button', { name: ' Submit' }).click();
});