import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://admin.onechanneladmin.com/signin?returnUrl=%2F');
  await page.getByRole('textbox', { name: 'Email address' }).click();
  await page.getByRole('textbox', { name: 'Email address' }).fill('princy@onechanneladmin.com');
  await page.locator('input[name="password"]').click();
  await page.locator('input[name="password"]').fill('beR60ElTpm0?YbW');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.waitForLoadState('networkidle');
  await page.getByRole('button', { name: 'Channel' }).click();
  await page.getByRole('link', { name: 'eBay' }).waitFor({ state: 'visible' });
  await page.getByRole('link', { name: 'eBay' }).click();
  await page.waitForLoadState('networkidle');
  await page.getByRole('link', { name: 'Settings' }).click();
  await page.getByLabel('General').getByRole('button').filter({ hasText: /^$/ }).click();
  await page.locator('#inputdiv').nth(1).click();
  await page.getByRole('tab', { name: 'Fulfillment Policies' }).click();
  await page.getByRole('tab', { name: 'General' }).click();
  await page.getByRole('tab', { name: 'Fulfillment Policies' }).click();
  await page.getByRole('button', { name: ' Add New' }).click();
  await page.locator('.p-dropdown.p-component.p-inputwrapper.width-100perc > .p-dropdown-trigger').first().click();
  await page.getByRole('option', { name: 'MOTORS_VEHICLES', exact: true }).click();
  await page.locator('.p-grid > div:nth-child(2) > .p-dropdown > .p-dropdown-trigger').click();
  await page.getByRole('option', { name: 'EBAY US' }).click();
  await page.getByRole('textbox', { name: 'Enter Policy Name' }).click();
  await page.getByRole('textbox', { name: 'Enter Policy Name' }).fill('one');
  await page.locator('div:nth-child(4) > .p-dropdown > .p-dropdown-trigger').click();
  await page.getByRole('option', { name: 'True' }).click();
  await page.locator('div:nth-child(5) > .p-dropdown > .p-dropdown-trigger').click();
  await page.getByRole('option', { name: 'Days' }).click();
  await page.locator('div:nth-child(6) > .p-dropdown > .p-dropdown-trigger').click();
  await page.getByRole('option', { name: '2' }).click();
  await page.locator('.p-grid > div:nth-child(7) > .p-dropdown > .p-dropdown-trigger').click();
  await page.getByRole('option', { name: 'CALCULATED' }).click();
  await page.locator('div:nth-child(8) > .p-dropdown > .p-dropdown-trigger').click();
  await page.getByRole('option', { name: 'INTERNATIONAL' }).click();
  await page.locator('div:nth-child(9) > .p-dropdown > .p-dropdown-trigger').click();
  await page.getByRole('option', { name: 'True' }).click();
  await page.locator('div:nth-child(10) > .p-dropdown > .p-dropdown-trigger').click();
  await page.getByRole('option', { name: 'GENERIC' }).click();
  await page.locator('div:nth-child(11) > .p-dropdown > .p-dropdown-trigger').click();
  await page.getByRole('option', { name: 'UPS3rdDay' }).click();
  await page.locator('div').filter({ hasText: /^empty$/ }).click();
  await page.locator('.p-dropdown.p-component.p-inputwrapper.width-100perc.p-focus > .p-dropdown-trigger').click();
  await page.locator('.p-dropdown.p-component.p-inputwrapper.width-100perc.p-focus > .p-dropdown-trigger').click();
  await page.getByRole('option', { name: 'USD' }).click();
  await page.getByRole('textbox', { name: 'Enter Value' }).click();
  await page.getByRole('textbox', { name: 'Enter Value' }).fill('100');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('tab', { name: 'Return Policies' }).click();
  await page.getByRole('tab', { name: 'Payment Policies' }).click();
  await page.getByRole('tab', { name: 'Vero Policies' }).click();
  await page.getByRole('tab', { name: ' Vero Policies' }).click();
  await page.getByRole('tab', { name: 'Description Template' }).click();
});