import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://admin.onechanneladmin.com/signin?returnUrl=%2F');
  await page.getByRole('textbox', { name: 'Email address' }).click();
  await page.getByRole('textbox', { name: 'Email address' }).fill('princy@onechanneladmin.com');
  await page.locator('input[name="password"]').click();
  await page.locator('input[name="password"]').fill('beR60ElTpm0?YbW');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('button', { name: 'Channel' }).click();
  await page.getByRole('link', { name: 'Repricer' }).click();
  await page.getByRole('tab', { name: 'Assign Rules' }).click();
  await page.getByRole('tab', { name: 'Rules', exact: true }).click();
  await page.getByRole('button', { name: ' Add New' }).click();
  await page.getByRole('textbox', { name: 'Name' }).click();
  await page.getByRole('textbox', { name: 'Name' }).fill('one');
  await page.getByRole('textbox', { name: 'Product Count' }).click();
  await page.getByRole('textbox', { name: 'Product Count' }).fill('2');
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(1).click();
  await page.getByRole('option', { name: 'Active' }).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(2).click();
  await page.getByRole('option', { name: 'Beat by' }).click();
  await page.locator('button').nth(3).click();
  await page.locator('button').nth(3).click();
  await page.locator('button').nth(5).click();
  await page.locator('.p-xl-12 > .p-dropdown > .p-dropdown-trigger').click();
  await page.getByRole('option', { name: 'New' }).click();
  await page.locator('div:nth-child(2) > .p-inputnumber > .p-inputnumber-button-group > .p-inputnumber-button.p-inputnumber-button-up').click();
  await page.locator('.p-xl-12 > .p-grid > div:nth-child(3) > .p-inputnumber > .p-inputnumber-button-group > .p-inputnumber-button.p-inputnumber-button-up').click();
  await page.locator('.p-xl-12 > .p-grid > div:nth-child(4) > .p-dropdown > .p-dropdown-trigger').click();
  await page.getByRole('option', { name: 'Only Compete with' }).click();
  await page.getByRole('listitem').nth(5).click();
  await page.getByRole('button', { name: ' Save' }).click();
});