import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://admin.onechanneladmin.com/signin?returnUrl=%2F');
  await page.getByRole('textbox', { name: 'Email address' }).click();
  await page.getByRole('textbox', { name: 'Email address' }).fill('');
  await page.getByRole('textbox', { name: 'Email address' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Email address' }).fill('princy@onechanneladmin.com');
  await page.locator('input[name="password"]').click();
  await page.locator('input[name="password"]').fill('beR60ElTpm0?YbW');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('button', { name: 'Catalog' }).click();
  await page.getByRole('link', { name: 'Labels' }).click();
  await page.getByRole('tab', { name: 'Flags' }).click();
  await page.getByRole('row', { name: ' Name' }).getByRole('checkbox').click();
  await page.getByRole('columnheader', { name: ' ' }).getByRole('checkbox').click();
  await page.getByRole('tab', { name: 'Channels' }).click();
  await page.getByRole('tab', { name: 'Flags' }).click();
  await page.getByRole('row', { name: ' Name' }).locator('i').click();
  await page.getByText('0').click();
  await page.locator('div').filter({ hasText: /^Unselect All$/ }).click();
  await page.getByRole('tab', { name: 'Marketplaces' }).click();
  await page.getByRole('menuitem', { name: 'Amazon US' }).click();
  await page.getByRole('tab', { name: 'Re Order Category' }).click();
  await page.getByRole('searchbox', { name: 'Global Search' }).click();
  await page.getByRole('searchbox', { name: 'Global Search' }).press('CapsLock');
  await page.getByRole('searchbox', { name: 'Global Search' }).fill('VCVC');
  await page.getByRole('button', { name: ' Save' }).click();
  await page.getByRole('button', { name: ' New Category' }).click();
  await page.getByRole('textbox', { name: 'Enter Category' }).click();
  await page.getByRole('textbox', { name: 'Enter Category' }).fill('MCMC');
  await page.getByRole('textbox', { name: 'Enter Category' }).press('CapsLock');
  await page.getByRole('button', { name: ' Cancel' }).click();
  await page.getByRole('tab', { name: 'HCPC Management' }).click();
  await page.getByRole('row', { name: 'ONE123 $10 $20 $30 $40 ' }).getByRole('checkbox').click();
  await page.getByRole('button', { name: ' Actions ' }).click();
  await page.getByText('Delete').click();
  await page.getByRole('button', { name: 'Yes' }).click();
  await page.getByRole('row', { name: ' ONE123 $10 $20 $30 $40 ' }).locator('button').click();
  await page.getByRole('button', { name: 'Yes' }).click();
  await page.getByRole('button', { name: ' Create HCPC' }).click();
  await page.getByRole('textbox', { name: 'HCPC Code' }).click();
  await page.getByRole('textbox', { name: 'HCPC Code' }).fill('one');
  await page.getByRole('spinbutton', { name: 'Enter Daily Value' }).click();
  await page.getByRole('spinbutton', { name: 'Enter 1 Week Value' }).click();
  await page.getByRole('spinbutton', { name: 'Enter 2 Week Value' }).click();
  await page.getByRole('spinbutton', { name: 'Enter 4 Week Value' }).click();
  await page.getByRole('button', { name: ' Submit' }).click();
  await page.getByRole('tab', { name: 'Re Order Category' }).click();
  await page.getByRole('button', { name: ' New Category' }).click();
  await page.getByRole('textbox', { name: 'Enter Category' }).click();
  await page.getByRole('textbox', { name: 'Enter Category' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter Category' }).fill('M');
  await page.getByRole('textbox', { name: 'Enter Category' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter Category' }).fill('Mn');
  await page.getByRole('textbox', { name: 'Enter Category' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter Category' }).fill('MnC');
  await page.getByRole('textbox', { name: 'Enter Category' }).press('CapsLock');
  await page.getByRole('button', { name: ' Submit' }).click();
  await page.getByRole('button', { name: ' Save' }).click();
});