import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://admin.onechanneladmin.com/signin?returnUrl=%2F');
  await page.getByRole('textbox', { name: 'Email address' }).click();
  await page.getByRole('textbox', { name: 'Email address' }).fill('princy@onechanneladmin.com');
  await page.locator('input[name="password"]').click();
  await page.locator('input[name="password"]').fill('beR60ElTpm0?YbW');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('button', { name: 'Catalog' }).click();
  await page.getByRole('link', { name: 'Pricing' }).click();
  await page.getByRole('tab', { name: 'Shipping' }).click();
  await page.getByRole('tabpanel', { name: 'Shipping' }).locator('i').click();
  await page.getByText('Select All 187416 records').click();
  await page.getByRole('columnheader', { name: ' ' }).locator('i').click();
  await page.getByRole('columnheader', { name: ' ' }).locator('i').click();
  await page.getByText('Unselect All').click();
  await page.getByRole('button', { name: ' Columns' }).click();
  await page.locator('.field-checkbox > .p-checkbox > .p-checkbox-box').click();
  await page.locator('.p-checkbox-box.p-highlight').first().click();
  await page.getByRole('button', { name: 'Apply' }).click();
  await page.getByRole('button', { name: ' Columns' }).click();
  await page.getByRole('button', { name: 'Reset' }).click();
  await page.getByRole('button', { name: ' Export' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('textbox', { name: 'Report Name' }).click();
  await page.getByRole('textbox', { name: 'Report Name' }).fill('1');
  await page.getByRole('button', { name: 'Create Report' }).click();
  await page.getByRole('button', { name: '5' }).click();
  await page.locator('.p-paginator-last').click();
});